org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# إيقاف كاش Kotlin التزايدي لمنع قفل الملفات
kotlin.incremental=false

# تفعيل دعم Kotlin المدمج الجديد لـ AGP 9+
android.builtInKotlin=true
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
